// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: static_layer_setting.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_static_5flayer_5fsetting_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_static_5flayer_5fsetting_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_static_5flayer_5fsetting_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_static_5flayer_5fsetting_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_static_5flayer_5fsetting_2eproto;
namespace hero_costmap {
class ParaStaticLayer;
class ParaStaticLayerDefaultTypeInternal;
extern ParaStaticLayerDefaultTypeInternal _ParaStaticLayer_default_instance_;
}  // namespace hero_costmap
PROTOBUF_NAMESPACE_OPEN
template<> ::hero_costmap::ParaStaticLayer* Arena::CreateMaybeMessage<::hero_costmap::ParaStaticLayer>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace hero_costmap {

// ===================================================================

class ParaStaticLayer PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hero_costmap.ParaStaticLayer) */ {
 public:
  inline ParaStaticLayer() : ParaStaticLayer(nullptr) {};
  virtual ~ParaStaticLayer();

  ParaStaticLayer(const ParaStaticLayer& from);
  ParaStaticLayer(ParaStaticLayer&& from) noexcept
    : ParaStaticLayer() {
    *this = ::std::move(from);
  }

  inline ParaStaticLayer& operator=(const ParaStaticLayer& from) {
    CopyFrom(from);
    return *this;
  }
  inline ParaStaticLayer& operator=(ParaStaticLayer&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ParaStaticLayer& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ParaStaticLayer* internal_default_instance() {
    return reinterpret_cast<const ParaStaticLayer*>(
               &_ParaStaticLayer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ParaStaticLayer& a, ParaStaticLayer& b) {
    a.Swap(&b);
  }
  inline void Swap(ParaStaticLayer* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ParaStaticLayer* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ParaStaticLayer* New() const final {
    return CreateMaybeMessage<ParaStaticLayer>(nullptr);
  }

  ParaStaticLayer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ParaStaticLayer>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ParaStaticLayer& from);
  void MergeFrom(const ParaStaticLayer& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ParaStaticLayer* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hero_costmap.ParaStaticLayer";
  }
  protected:
  explicit ParaStaticLayer(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_static_5flayer_5fsetting_2eproto);
    return ::descriptor_table_static_5flayer_5fsetting_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTopicNameFieldNumber = 8,
    kFirstMapOnlyFieldNumber = 1,
    kSubscribeToUpdatesFieldNumber = 2,
    kTrackUnknownSpaceFieldNumber = 3,
    kUseMaximumFieldNumber = 4,
    kUnknownCostValueFieldNumber = 5,
    kLethalThresholdFieldNumber = 7,
    kTrinaryMapFieldNumber = 6,
    kIsRawRosmessageFieldNumber = 9,
    kIsDebugFieldNumber = 10,
  };
  // required string topic_name = 8;
  bool has_topic_name() const;
  private:
  bool _internal_has_topic_name() const;
  public:
  void clear_topic_name();
  const std::string& topic_name() const;
  void set_topic_name(const std::string& value);
  void set_topic_name(std::string&& value);
  void set_topic_name(const char* value);
  void set_topic_name(const char* value, size_t size);
  std::string* mutable_topic_name();
  std::string* release_topic_name();
  void set_allocated_topic_name(std::string* topic_name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_topic_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_topic_name(
      std::string* topic_name);
  private:
  const std::string& _internal_topic_name() const;
  void _internal_set_topic_name(const std::string& value);
  std::string* _internal_mutable_topic_name();
  public:

  // required bool first_map_only = 1;
  bool has_first_map_only() const;
  private:
  bool _internal_has_first_map_only() const;
  public:
  void clear_first_map_only();
  bool first_map_only() const;
  void set_first_map_only(bool value);
  private:
  bool _internal_first_map_only() const;
  void _internal_set_first_map_only(bool value);
  public:

  // required bool subscribe_to_updates = 2;
  bool has_subscribe_to_updates() const;
  private:
  bool _internal_has_subscribe_to_updates() const;
  public:
  void clear_subscribe_to_updates();
  bool subscribe_to_updates() const;
  void set_subscribe_to_updates(bool value);
  private:
  bool _internal_subscribe_to_updates() const;
  void _internal_set_subscribe_to_updates(bool value);
  public:

  // required bool track_unknown_space = 3;
  bool has_track_unknown_space() const;
  private:
  bool _internal_has_track_unknown_space() const;
  public:
  void clear_track_unknown_space();
  bool track_unknown_space() const;
  void set_track_unknown_space(bool value);
  private:
  bool _internal_track_unknown_space() const;
  void _internal_set_track_unknown_space(bool value);
  public:

  // required bool use_maximum = 4;
  bool has_use_maximum() const;
  private:
  bool _internal_has_use_maximum() const;
  public:
  void clear_use_maximum();
  bool use_maximum() const;
  void set_use_maximum(bool value);
  private:
  bool _internal_use_maximum() const;
  void _internal_set_use_maximum(bool value);
  public:

  // required int32 unknown_cost_value = 5;
  bool has_unknown_cost_value() const;
  private:
  bool _internal_has_unknown_cost_value() const;
  public:
  void clear_unknown_cost_value();
  ::PROTOBUF_NAMESPACE_ID::int32 unknown_cost_value() const;
  void set_unknown_cost_value(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_unknown_cost_value() const;
  void _internal_set_unknown_cost_value(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 lethal_threshold = 7;
  bool has_lethal_threshold() const;
  private:
  bool _internal_has_lethal_threshold() const;
  public:
  void clear_lethal_threshold();
  ::PROTOBUF_NAMESPACE_ID::int32 lethal_threshold() const;
  void set_lethal_threshold(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_lethal_threshold() const;
  void _internal_set_lethal_threshold(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required bool trinary_map = 6;
  bool has_trinary_map() const;
  private:
  bool _internal_has_trinary_map() const;
  public:
  void clear_trinary_map();
  bool trinary_map() const;
  void set_trinary_map(bool value);
  private:
  bool _internal_trinary_map() const;
  void _internal_set_trinary_map(bool value);
  public:

  // required bool is_raw_rosmessage = 9;
  bool has_is_raw_rosmessage() const;
  private:
  bool _internal_has_is_raw_rosmessage() const;
  public:
  void clear_is_raw_rosmessage();
  bool is_raw_rosmessage() const;
  void set_is_raw_rosmessage(bool value);
  private:
  bool _internal_is_raw_rosmessage() const;
  void _internal_set_is_raw_rosmessage(bool value);
  public:

  // required bool is_debug = 10;
  bool has_is_debug() const;
  private:
  bool _internal_has_is_debug() const;
  public:
  void clear_is_debug();
  bool is_debug() const;
  void set_is_debug(bool value);
  private:
  bool _internal_is_debug() const;
  void _internal_set_is_debug(bool value);
  public:

  // @@protoc_insertion_point(class_scope:hero_costmap.ParaStaticLayer)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr topic_name_;
  bool first_map_only_;
  bool subscribe_to_updates_;
  bool track_unknown_space_;
  bool use_maximum_;
  ::PROTOBUF_NAMESPACE_ID::int32 unknown_cost_value_;
  ::PROTOBUF_NAMESPACE_ID::int32 lethal_threshold_;
  bool trinary_map_;
  bool is_raw_rosmessage_;
  bool is_debug_;
  friend struct ::TableStruct_static_5flayer_5fsetting_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ParaStaticLayer

// required bool first_map_only = 1;
inline bool ParaStaticLayer::_internal_has_first_map_only() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ParaStaticLayer::has_first_map_only() const {
  return _internal_has_first_map_only();
}
inline void ParaStaticLayer::clear_first_map_only() {
  first_map_only_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool ParaStaticLayer::_internal_first_map_only() const {
  return first_map_only_;
}
inline bool ParaStaticLayer::first_map_only() const {
  // @@protoc_insertion_point(field_get:hero_costmap.ParaStaticLayer.first_map_only)
  return _internal_first_map_only();
}
inline void ParaStaticLayer::_internal_set_first_map_only(bool value) {
  _has_bits_[0] |= 0x00000002u;
  first_map_only_ = value;
}
inline void ParaStaticLayer::set_first_map_only(bool value) {
  _internal_set_first_map_only(value);
  // @@protoc_insertion_point(field_set:hero_costmap.ParaStaticLayer.first_map_only)
}

// required bool subscribe_to_updates = 2;
inline bool ParaStaticLayer::_internal_has_subscribe_to_updates() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool ParaStaticLayer::has_subscribe_to_updates() const {
  return _internal_has_subscribe_to_updates();
}
inline void ParaStaticLayer::clear_subscribe_to_updates() {
  subscribe_to_updates_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool ParaStaticLayer::_internal_subscribe_to_updates() const {
  return subscribe_to_updates_;
}
inline bool ParaStaticLayer::subscribe_to_updates() const {
  // @@protoc_insertion_point(field_get:hero_costmap.ParaStaticLayer.subscribe_to_updates)
  return _internal_subscribe_to_updates();
}
inline void ParaStaticLayer::_internal_set_subscribe_to_updates(bool value) {
  _has_bits_[0] |= 0x00000004u;
  subscribe_to_updates_ = value;
}
inline void ParaStaticLayer::set_subscribe_to_updates(bool value) {
  _internal_set_subscribe_to_updates(value);
  // @@protoc_insertion_point(field_set:hero_costmap.ParaStaticLayer.subscribe_to_updates)
}

// required bool track_unknown_space = 3;
inline bool ParaStaticLayer::_internal_has_track_unknown_space() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool ParaStaticLayer::has_track_unknown_space() const {
  return _internal_has_track_unknown_space();
}
inline void ParaStaticLayer::clear_track_unknown_space() {
  track_unknown_space_ = false;
  _has_bits_[0] &= ~0x00000008u;
}
inline bool ParaStaticLayer::_internal_track_unknown_space() const {
  return track_unknown_space_;
}
inline bool ParaStaticLayer::track_unknown_space() const {
  // @@protoc_insertion_point(field_get:hero_costmap.ParaStaticLayer.track_unknown_space)
  return _internal_track_unknown_space();
}
inline void ParaStaticLayer::_internal_set_track_unknown_space(bool value) {
  _has_bits_[0] |= 0x00000008u;
  track_unknown_space_ = value;
}
inline void ParaStaticLayer::set_track_unknown_space(bool value) {
  _internal_set_track_unknown_space(value);
  // @@protoc_insertion_point(field_set:hero_costmap.ParaStaticLayer.track_unknown_space)
}

// required bool use_maximum = 4;
inline bool ParaStaticLayer::_internal_has_use_maximum() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool ParaStaticLayer::has_use_maximum() const {
  return _internal_has_use_maximum();
}
inline void ParaStaticLayer::clear_use_maximum() {
  use_maximum_ = false;
  _has_bits_[0] &= ~0x00000010u;
}
inline bool ParaStaticLayer::_internal_use_maximum() const {
  return use_maximum_;
}
inline bool ParaStaticLayer::use_maximum() const {
  // @@protoc_insertion_point(field_get:hero_costmap.ParaStaticLayer.use_maximum)
  return _internal_use_maximum();
}
inline void ParaStaticLayer::_internal_set_use_maximum(bool value) {
  _has_bits_[0] |= 0x00000010u;
  use_maximum_ = value;
}
inline void ParaStaticLayer::set_use_maximum(bool value) {
  _internal_set_use_maximum(value);
  // @@protoc_insertion_point(field_set:hero_costmap.ParaStaticLayer.use_maximum)
}

// required int32 unknown_cost_value = 5;
inline bool ParaStaticLayer::_internal_has_unknown_cost_value() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool ParaStaticLayer::has_unknown_cost_value() const {
  return _internal_has_unknown_cost_value();
}
inline void ParaStaticLayer::clear_unknown_cost_value() {
  unknown_cost_value_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ParaStaticLayer::_internal_unknown_cost_value() const {
  return unknown_cost_value_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ParaStaticLayer::unknown_cost_value() const {
  // @@protoc_insertion_point(field_get:hero_costmap.ParaStaticLayer.unknown_cost_value)
  return _internal_unknown_cost_value();
}
inline void ParaStaticLayer::_internal_set_unknown_cost_value(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000020u;
  unknown_cost_value_ = value;
}
inline void ParaStaticLayer::set_unknown_cost_value(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_unknown_cost_value(value);
  // @@protoc_insertion_point(field_set:hero_costmap.ParaStaticLayer.unknown_cost_value)
}

// required bool trinary_map = 6;
inline bool ParaStaticLayer::_internal_has_trinary_map() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool ParaStaticLayer::has_trinary_map() const {
  return _internal_has_trinary_map();
}
inline void ParaStaticLayer::clear_trinary_map() {
  trinary_map_ = false;
  _has_bits_[0] &= ~0x00000080u;
}
inline bool ParaStaticLayer::_internal_trinary_map() const {
  return trinary_map_;
}
inline bool ParaStaticLayer::trinary_map() const {
  // @@protoc_insertion_point(field_get:hero_costmap.ParaStaticLayer.trinary_map)
  return _internal_trinary_map();
}
inline void ParaStaticLayer::_internal_set_trinary_map(bool value) {
  _has_bits_[0] |= 0x00000080u;
  trinary_map_ = value;
}
inline void ParaStaticLayer::set_trinary_map(bool value) {
  _internal_set_trinary_map(value);
  // @@protoc_insertion_point(field_set:hero_costmap.ParaStaticLayer.trinary_map)
}

// required int32 lethal_threshold = 7;
inline bool ParaStaticLayer::_internal_has_lethal_threshold() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool ParaStaticLayer::has_lethal_threshold() const {
  return _internal_has_lethal_threshold();
}
inline void ParaStaticLayer::clear_lethal_threshold() {
  lethal_threshold_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ParaStaticLayer::_internal_lethal_threshold() const {
  return lethal_threshold_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ParaStaticLayer::lethal_threshold() const {
  // @@protoc_insertion_point(field_get:hero_costmap.ParaStaticLayer.lethal_threshold)
  return _internal_lethal_threshold();
}
inline void ParaStaticLayer::_internal_set_lethal_threshold(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000040u;
  lethal_threshold_ = value;
}
inline void ParaStaticLayer::set_lethal_threshold(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_lethal_threshold(value);
  // @@protoc_insertion_point(field_set:hero_costmap.ParaStaticLayer.lethal_threshold)
}

// required string topic_name = 8;
inline bool ParaStaticLayer::_internal_has_topic_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ParaStaticLayer::has_topic_name() const {
  return _internal_has_topic_name();
}
inline void ParaStaticLayer::clear_topic_name() {
  topic_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ParaStaticLayer::topic_name() const {
  // @@protoc_insertion_point(field_get:hero_costmap.ParaStaticLayer.topic_name)
  return _internal_topic_name();
}
inline void ParaStaticLayer::set_topic_name(const std::string& value) {
  _internal_set_topic_name(value);
  // @@protoc_insertion_point(field_set:hero_costmap.ParaStaticLayer.topic_name)
}
inline std::string* ParaStaticLayer::mutable_topic_name() {
  // @@protoc_insertion_point(field_mutable:hero_costmap.ParaStaticLayer.topic_name)
  return _internal_mutable_topic_name();
}
inline const std::string& ParaStaticLayer::_internal_topic_name() const {
  return topic_name_.Get();
}
inline void ParaStaticLayer::_internal_set_topic_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  topic_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ParaStaticLayer::set_topic_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  topic_name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:hero_costmap.ParaStaticLayer.topic_name)
}
inline void ParaStaticLayer::set_topic_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  topic_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:hero_costmap.ParaStaticLayer.topic_name)
}
inline void ParaStaticLayer::set_topic_name(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  topic_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:hero_costmap.ParaStaticLayer.topic_name)
}
inline std::string* ParaStaticLayer::_internal_mutable_topic_name() {
  _has_bits_[0] |= 0x00000001u;
  return topic_name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ParaStaticLayer::release_topic_name() {
  // @@protoc_insertion_point(field_release:hero_costmap.ParaStaticLayer.topic_name)
  if (!_internal_has_topic_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return topic_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ParaStaticLayer::set_allocated_topic_name(std::string* topic_name) {
  if (topic_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  topic_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), topic_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:hero_costmap.ParaStaticLayer.topic_name)
}
inline std::string* ParaStaticLayer::unsafe_arena_release_topic_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:hero_costmap.ParaStaticLayer.topic_name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return topic_name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ParaStaticLayer::unsafe_arena_set_allocated_topic_name(
    std::string* topic_name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (topic_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  topic_name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      topic_name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hero_costmap.ParaStaticLayer.topic_name)
}

// required bool is_raw_rosmessage = 9;
inline bool ParaStaticLayer::_internal_has_is_raw_rosmessage() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool ParaStaticLayer::has_is_raw_rosmessage() const {
  return _internal_has_is_raw_rosmessage();
}
inline void ParaStaticLayer::clear_is_raw_rosmessage() {
  is_raw_rosmessage_ = false;
  _has_bits_[0] &= ~0x00000100u;
}
inline bool ParaStaticLayer::_internal_is_raw_rosmessage() const {
  return is_raw_rosmessage_;
}
inline bool ParaStaticLayer::is_raw_rosmessage() const {
  // @@protoc_insertion_point(field_get:hero_costmap.ParaStaticLayer.is_raw_rosmessage)
  return _internal_is_raw_rosmessage();
}
inline void ParaStaticLayer::_internal_set_is_raw_rosmessage(bool value) {
  _has_bits_[0] |= 0x00000100u;
  is_raw_rosmessage_ = value;
}
inline void ParaStaticLayer::set_is_raw_rosmessage(bool value) {
  _internal_set_is_raw_rosmessage(value);
  // @@protoc_insertion_point(field_set:hero_costmap.ParaStaticLayer.is_raw_rosmessage)
}

// required bool is_debug = 10;
inline bool ParaStaticLayer::_internal_has_is_debug() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool ParaStaticLayer::has_is_debug() const {
  return _internal_has_is_debug();
}
inline void ParaStaticLayer::clear_is_debug() {
  is_debug_ = false;
  _has_bits_[0] &= ~0x00000200u;
}
inline bool ParaStaticLayer::_internal_is_debug() const {
  return is_debug_;
}
inline bool ParaStaticLayer::is_debug() const {
  // @@protoc_insertion_point(field_get:hero_costmap.ParaStaticLayer.is_debug)
  return _internal_is_debug();
}
inline void ParaStaticLayer::_internal_set_is_debug(bool value) {
  _has_bits_[0] |= 0x00000200u;
  is_debug_ = value;
}
inline void ParaStaticLayer::set_is_debug(bool value) {
  _internal_set_is_debug(value);
  // @@protoc_insertion_point(field_set:hero_costmap.ParaStaticLayer.is_debug)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace hero_costmap

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_static_5flayer_5fsetting_2eproto
